import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"
import { Toaster } from "sonner";
import { cookies } from "next/headers";
import { createClient } from "@/lib/supabase/server";
import { BusinessProvider } from "@/components/providers/BusinessProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Booking App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies()
  const supabase = createClient(cookieStore)

  const businessId = process.env.NEXT_PUBLIC_BUSINESS_ID

  const { data: business, error } = await supabase.from("businesses").select("*").eq("id", businessId).single()

  if (error || !business) {
    return <html><body><h1>Website Configuration Error</h1></body></html>
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <BusinessProvider value={business}>
          <Navbar />
          <main className="max-w-7xl flex-1 mx-auto w-full px-2 py-8 md:px-6 lg:px-8">
            {children}
          </main>
          <Footer />
          <Toaster closeButton />
        </BusinessProvider>
      </body>
    </html>
  );
}
